version: "3.2"

services:
  mariadb:
    image: elestio/mariadb:10.9
    restart: always
    hostname: mariadb
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "172.17.0.1:50778:3306"

  glpi:
    image: diouxx/glpi
    restart: always
    hostname: glpi
    ports:
      - "172.17.0.1:22571:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels

  pma:
    image: phpmyadmin
    restart: always
    links:
      - mariadb:mariadb
    ports:
      - "172.17.0.1:22811:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: pixelfed
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mariadb
